### ISSUE TITLE
Lost features with WordPress 5.8

### ISSUE THREAD

**Issue by tmmbecker** [Automattic/republication-tracker-tool#123]
In the new Widgets page, these options are now gone:

Title Link
Background
Hidden on Desktop/Tablet/Phones

![Screen Shot on 2021-08-10 at 20-01-06](https://user-images.githubusercontent.com/22805865/128949944-2dc85082-16c4-4273-8057-ca753e527452.png)

We'll need to address that as part of the shift to a block for this.

**Comment by benlk** [comment]
Odd question: is that a Largo site? I ask because [those three options were provided by the Largo theme](https://github.com/WPBuddy/largo/blob/590181982d22a5444eb3c5ccca58ea8b56db12f7/inc/widgets.php#L131-L163), which is currently maintained by WPBuddy but which used to be maintained by this plugin's original creator, INN Labs. If the affected site is using Largo, this may be a Largo bug, not a bug in Republication Tracker Tool.

The docs in https://github.com/Automattic/republication-tracker-tool/blob/c847f0a95c9cdb9c0bd089ef45880e56867ffe1b/docs/adding-republish-button-to-posts.md are using Largo as an example theme.

**Comment by tmmbecker** [comment]
@benlk this is not a Largo site and it's not clear from the [docs here](https://github.com/Automattic/republication-tracker-tool/blob/master/docs/adding-republish-button-to-posts.md) that this was added by the Largo theme. Thanks!
