### ISSUE TITLE
Is this AMP compatible?

### ISSUE THREAD

**Issue by benlk** [Automattic/republication-tracker-tool#57]
This plugin's custom modal is probably affected by the same problem as the Trust Indicators plugin, in https://github.com/INN/trust-indicators/issues/91

We could probably solve this with something like

```php
function republication_widget_if_amp_endpoint( $hide, $post ) {
   if ( function_exists( 'is_amp_endpoint' ) && is_amp_endpoint() ) {
       return true;
   }
   return $hide;
}
if ( function_exists( 'is_amp_endpoint' ) ) {
   add_filter( 'hide_republication_widget', 'republication_widget_if_amp_endpoint', 10, 2 );
}
```

**Comment by kaylima** [comment]
More information from a site using the plugin:

----------------------

The Republication Tracker Tools seems to be incompatible with AMP. I’m consistently getting an “invalid attribute”  for onclick. I’ve attached a screenshot of the full message. Seems to consistently be the use of JS <script> tags.

Here’s the error message in text as well:

Information
AMP does not allow the use of JS <script> tags unless they are for loading AMP components, which are added automatically by the AMP plugin. For any page to be served as AMP, all invalid script tags must be removed from the page. Instead of custom or third-party JS, please consider using AMP components and functionality such as amp-bind and actions and events (as opposed to JS event handler attributes like onclick). Some custom JS can be added if encapsulated in the amp-script. Learn more about how AMP works.

If all invalid markup is “removed” the page will be served as AMP. However, the impact that the removal has on the page must be assessed to determine if the result is acceptable. If any invalid markup is “kept” then the page will not be served as AMP.

Error code
DISALLOWED_ATTR

Invalid markup
<button onclick="copyToClipboard('#republication-tracker-tool-shareable-content')">

Element attributes
onclick	copyToClipboard('#republication-tracker-tool-shareable-content')

Attribute name
onclick

Parent element
button

**Comment by joshdarby** [comment]
@kaylima This wasn't developed to be AMP compatible (as it stands) since the idea of AMP is to reduce the size of pages by not including Javascript in order to make them load faster. @benlk's solution above would fix the issue by hiding the widget on AMP pages, or the plugin can be updated to use AMP compatible JS 
https://amp.dev/documentation/guides-and-tutorials/develop/custom-javascript/

**Comment by kaylima** [comment]
Another site, using the AMP plugin. has relayed an issue where the modal is not showing on click. I'm assuming this is related to this issue. 

On clicking the Republish This Story button:
- full screen is grayed out with an overlay but modal and elements within the model do not show
- dev tools show that the modal element is there, it's just not rendering on the front-end

![Screen Shot 2020-11-06 at 1 32 58 PM](https://user-images.githubusercontent.com/15877728/98412145-abf0b800-2034-11eb-92d4-6be4e685eea4.png)
